//Const For Enums:
const POSITIONS = [
  // Engineering
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "QA Engineer",
  "Security Engineer",
  "Machine Learning Engineer",
  "Embedded Systems Engineer",
  "Blockchain Developer",

  // Data & Analytics
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Business Intelligence Analyst",
  "AI Research Scientist",

  // Product
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Product Owner",

  // Design
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Motion Designer",
  "Brand Designer",

  //Marketing
  "Marketing Manager",
  "Content Writer",
  "SEO Specialist",
  "Social Media Manager",
  "Growth Marketer",
  "Email Marketing Specialist",
  "Performance Marketer",

  //Sales
  "Sales Executive",
  "Business Development Manager",
  "Account Manager",
  "Sales Development Representative",
  "Enterprise Sales Manager",

  //Finance
  "Financial Analyst",
  "Accountant",
  "Finance Manager",
  "Chief Financial Officer",
  "Investment Analyst",

  //Human Resources
  "HR Manager",
  "HR Generalist",
  "Talent Acquisition Specialist",
  "Compensation & Benefits Analyst",
  "HR Business Partner",

  //Operations
  "Operations Manager",
  "Project Manager",
  "Scrum Master",
  "Business Analyst",
  "Supply Chain Manager",

  //Legal
  "Legal Counsel",
  "Compliance Officer",
  "Contract Manager",

  //Customer Support
  "Customer Support Specialist",
  "Technical Support Engineer",
  "Customer Success Manager",

  //Research
  "Research Scientist",
  "Research Analyst",
  "UX Researcher",
];
const EXPERIENCE_LEVELS = [
  "Internship",
  "Entry Level", // 0–1 years
  "Junior", // 1–2 years
  "Mid Level", // 2–4 years
  "Senior", // 4–7 years
];
const HR_DESIGNATIONS = [
  //Entry Level
  "HR Intern",
  "HR Assistant",
  "HR Coordinator",
  "Recruitment Coordinator",
  "Talent Acquisition Coordinator",

  //Mid Level
  "HR Generalist",
  "HR Specialist",
  "Recruiter",
  "Talent Acquisition Specialist",
  "Compensation & Benefits Specialist",
  "Learning & Development Specialist",
  "Employee Relations Specialist",
  "HR Analyst",
  "People Operations Specialist",

  //Senior Level
  "Senior HR Generalist",
  "Senior Recruiter",
  "Senior Talent Acquisition Specialist",
  "HR Business Partner",
  "Senior HR Business Partner",
  "Compensation & Benefits Manager",
  "Learning & Development Manager",
  "Employee Relations Manager",
  "Workforce Planning Manager",

  //Management
  "HR Manager",
  "Senior HR Manager",
  "Talent Acquisition Manager",
  "People Operations Manager",
  "Recruitment Manager",
  "HR Operations Manager",
  "Organizational Development Manager",

  //Director Level
  "HR Director",
  "Director of Talent Acquisition",
  "Director of People Operations",
  "Director of Organizational Development",
  "Director of Compensation & Benefits",

  //VP Level
  "VP of Human Resources",
  "VP of People",
  "VP of Talent",

  //C-Level
  "Chief Human Resources Officer",
  "Chief People Officer",
  "Chief Talent Officer",
];
const DEPARTMENTS = [
  "Engineering",
  "Data & Analytics",
  "Product",
  "Design",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Operations",
  "Legal",
  "Customer Support",
  "Research",
];
const NEPAL_LOCATIONS = [
  // Koshi
  "Morang, Biratnagar",
  "Sunsari, Itahari",
  "Sunsari, Dharan",
  "Jhapa, Birtamod",
  "Jhapa, Mechinagar",
  "Ilam, Ilam",
  "Dhankuta, Dhankuta",
  "Udayapur, Gaighat",
  "Solukhumbu, Salleri",
  "Taplejung, Taplejung",
  "Sankhuwasabha, Khandbari",
  "Bhojpur, Bhojpur",
  "Terhathum, Myanglung",
  "Okhaldhunga, Okhaldhunga",
  "Khotang, Diktel",

  // Madhesh
  "Parsa, Birgunj",
  "Bara, Kalaiya",
  "Dhanusha, Janakpur",
  "Sarlahi, Malangwa",
  "Rautahat, Gaur",
  "Mahottari, Jaleshwar",
  "Siraha, Lahan",
  "Saptari, Rajbiraj",

  // Bagmati
  "Kathmandu, Kathmandu",
  "Kathmandu, Kirtipur",
  "Lalitpur, Lalitpur",
  "Bhaktapur, Bhaktapur",
  "Bhaktapur, Madhyapur Thimi",
  "Chitwan, Bharatpur",
  "Makwanpur, Hetauda",
  "Kavrepalanchok, Dhulikhel",
  "Kavrepalanchok, Banepa",
  "Sindhupalchok, Chautara",
  "Nuwakot, Bidur",
  "Dhading, Nilkantha",
  "Sindhuli, Sindhulimadi",
  "Ramechhap, Manthali",
  "Dolakha, Charikot",
  "Rasuwa, Dhunche",

  // Gandaki
  "Kaski, Pokhara",
  "Tanahun, Damauli",
  "Syangja, Waling",
  "Gorkha, Gorkha",
  "Lamjung, Besisahar",
  "Baglung, Baglung",
  "Parbat, Kushma",
  "Myagdi, Beni",
  "Mustang, Jomsom",
  "Manang, Chame",
  "Nawalpur, Kawasoti",

  // Lumbini
  "Rupandehi, Butwal",
  "Rupandehi, Siddharthanagar",
  "Banke, Nepalgunj",
  "Dang, Ghorahi",
  "Dang, Tulsipur",
  "Bardiya, Gulariya",
  "Kapilvastu, Taulihawa",
  "Nawalparasi, Parasi",
  "Palpa, Tansen",
  "Gulmi, Tamghas",
  "Arghakhanchi, Sandhikharka",
  "Pyuthan, Pyuthan",
  "Rolpa, Liwang",

  // Karnali
  "Surkhet, Birendranagar",
  "Jumla, Chandannath",
  "Dailekh, Narayan",
  "Salyan, Sharada",
  "Jajarkot, Khalanga",
  "Dolpa, Dunai",
  "Mugu, Gamgadhi",
  "Humla, Simikot",
  "Kalikot, Manma",
  "Western Rukum, Musikot",

  // Sudurpashchim
  "Kailali, Dhangadhi",
  "Kailali, Tikapur",
  "Kanchanpur, Mahendranagar",
  "Dadeldhura, Dadeldhura",
  "Doti, Dipayal",
  "Achham, Mangalsen",
  "Bajura, Martadi",
  "Bajhang, Chainpur",
  "Baitadi, Dasharathchand",
  "Darchula, Darchula",
];
const JOB_STATUS = ["Draft", "Published", "Closed"];
const INTERVIEW_TONE = [
  "formal", // structured, corporate style
  "casual", // relaxed, conversational
  "technical", // deep technical questions, problem solving
  "behavioral", // situation based, tell me about a time...
  "mixed", // combination of all
];
//Const For Mappings:
const Department = {
  ENGINEERING: "Engineering",
  DATA_ANALYTICS: "Data & Analytics",
  PRODUCT: "Product",
  DESIGN: "Design",
  MARKETING: "Marketing",
  SALES: "Sales",
  FINANCE: "Finance",
  HUMAN_RESOURCES: "Human Resources",
  OPERATIONS: "Operations",
  LEGAL: "Legal",
  CUSTOMER_SUPPORT: "Customer Support",
  RESEARCH: "Research",
};
const POSITION_DEPARTMENT_MAP = {
  // Engineering
  "Frontend Engineer": Department.ENGINEERING,
  "Backend Engineer": Department.ENGINEERING,
  "Full Stack Engineer": Department.ENGINEERING,
  "Mobile Engineer": Department.ENGINEERING,
  "DevOps Engineer": Department.ENGINEERING,
  "Site Reliability Engineer": Department.ENGINEERING,
  "QA Engineer": Department.ENGINEERING,
  "Security Engineer": Department.ENGINEERING,
  "Machine Learning Engineer": Department.ENGINEERING,
  "Embedded Systems Engineer": Department.ENGINEERING,
  "Blockchain Developer": Department.ENGINEERING,

  // Data & Analytics
  "Data Scientist": Department.DATA_ANALYTICS,
  "Data Analyst": Department.DATA_ANALYTICS,
  "Data Engineer": Department.DATA_ANALYTICS,
  "Business Intelligence Analyst": Department.DATA_ANALYTICS,
  "AI Research Scientist": Department.DATA_ANALYTICS,

  // Product
  "Product Manager": Department.PRODUCT,
  "Associate Product Manager": Department.PRODUCT,
  "Senior Product Manager": Department.PRODUCT,
  "Technical Product Manager": Department.PRODUCT,
  "Product Owner": Department.PRODUCT,

  // Design
  "UI Designer": Department.DESIGN,
  "UX Designer": Department.DESIGN,
  "Product Designer": Department.DESIGN,
  "Graphic Designer": Department.DESIGN,
  "Motion Designer": Department.DESIGN,
  "Brand Designer": Department.DESIGN,

  // Marketing
  "Marketing Manager": Department.MARKETING,
  "Content Writer": Department.MARKETING,
  "SEO Specialist": Department.MARKETING,
  "Social Media Manager": Department.MARKETING,
  "Growth Marketer": Department.MARKETING,
  "Email Marketing Specialist": Department.MARKETING,
  "Performance Marketer": Department.MARKETING,

  // Sales
  "Sales Executive": Department.SALES,
  "Business Development Manager": Department.SALES,
  "Account Manager": Department.SALES,
  "Sales Development Representative": Department.SALES,
  "Enterprise Sales Manager": Department.SALES,

  // Finance
  "Financial Analyst": Department.FINANCE,
  Accountant: Department.FINANCE,
  "Finance Manager": Department.FINANCE,
  "Chief Financial Officer": Department.FINANCE,
  "Investment Analyst": Department.FINANCE,

  // Human Resources
  "HR Manager": Department.HUMAN_RESOURCES,
  "HR Generalist": Department.HUMAN_RESOURCES,
  "Talent Acquisition Specialist": Department.HUMAN_RESOURCES,
  "Compensation & Benefits Analyst": Department.HUMAN_RESOURCES,
  "HR Business Partner": Department.HUMAN_RESOURCES,

  // Operations
  "Operations Manager": Department.OPERATIONS,
  "Project Manager": Department.OPERATIONS,
  "Scrum Master": Department.OPERATIONS,
  "Business Analyst": Department.OPERATIONS,
  "Supply Chain Manager": Department.OPERATIONS,

  // Legal
  "Legal Counsel": Department.LEGAL,
  "Compliance Officer": Department.LEGAL,
  "Contract Manager": Department.LEGAL,

  // Customer Support
  "Customer Support Specialist": Department.CUSTOMER_SUPPORT,
  "Technical Support Engineer": Department.CUSTOMER_SUPPORT,
  "Customer Success Manager": Department.CUSTOMER_SUPPORT,

  // Research
  "Research Scientist": Department.RESEARCH,
  "Research Analyst": Department.RESEARCH,
  "UX Researcher": Department.RESEARCH,
};
const POSITION_SKILLS = {
  //Engineering
  "Frontend Engineer": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Tailwind CSS",
    "Redux",
    "GraphQL",
    "REST APIs",
    "Git",
    "Webpack",
    "Vite",
    "Jest",
    "Cypress",
    "Figma",
    "Responsive Design",
  ],
  "Backend Engineer": [
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "FastAPI",
    "Java",
    "Spring Boot",
    "Go",
    "Ruby on Rails",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Redis",
    "REST APIs",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "AWS",
    "Git",
    "CI/CD",
  ],
  "Full Stack Engineer": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "PostgreSQL",
    "MongoDB",
    "REST APIs",
    "GraphQL",
    "Docker",
    "Git",
    "AWS",
    "Redis",
    "CI/CD",
    "Tailwind CSS",
  ],
  "Mobile Engineer": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Java",
    "Dart",
    "iOS Development",
    "Android Development",
    "Firebase",
    "REST APIs",
    "GraphQL",
    "Redux",
    "Git",
    "App Store Deployment",
    "Push Notifications",
  ],
  "DevOps Engineer": [
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Azure",
    "Terraform",
    "Ansible",
    "Jenkins",
    "CI/CD",
    "Linux",
    "Bash",
    "Python",
    "Nginx",
    "Git",
    "Prometheus",
    "Grafana",
    "Helm",
    "ArgoCD",
  ],
  "Site Reliability Engineer": [
    "Linux",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Terraform",
    "Python",
    "Bash",
    "Prometheus",
    "Grafana",
    "CI/CD",
    "Incident Management",
    "Load Balancing",
    "Nginx",
    "Git",
    "On-call Management",
  ],
  "QA Engineer": [
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "Cypress",
    "Jest",
    "Postman",
    "REST APIs",
    "SQL",
    "Git",
    "JIRA",
    "Test Planning",
    "Performance Testing",
    "JMeter",
    "Bug Tracking",
    "Agile",
  ],
  "Security Engineer": [
    "Network Security",
    "Penetration Testing",
    "OWASP",
    "AWS Security",
    "Cryptography",
    "SIEM",
    "Firewalls",
    "Linux",
    "Python",
    "Bash",
    "Vulnerability Assessment",
    "IAM",
    "Zero Trust",
    "GDPR Compliance",
  ],
  "Machine Learning Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "SQL",
    "MLflow",
    "Docker",
    "AWS SageMaker",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Feature Engineering",
    "Git",
    "Jupyter",
  ],
  "Embedded Systems Engineer": [
    "C",
    "C++",
    "RTOS",
    "Microcontrollers",
    "Arduino",
    "Raspberry Pi",
    "ARM Architecture",
    "Assembly",
    "I2C",
    "SPI",
    "UART",
    "CAN Bus",
    "PCB Design",
    "MATLAB",
    "Debugging",
    "Git",
  ],
  "Blockchain Developer": [
    "Solidity",
    "Ethereum",
    "Web3.js",
    "Ethers.js",
    "Smart Contracts",
    "Hardhat",
    "Truffle",
    "IPFS",
    "DeFi",
    "NFT",
    "Rust",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Git",
  ],

  //Data & Analytics
  "Data Scientist": [
    "Python",
    "R",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "SQL",
    "Tableau",
    "Power BI",
    "Statistics",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Data Visualization",
    "Jupyter",
    "Git",
  ],
  "Data Analyst": [
    "SQL",
    "Python",
    "Excel",
    "Tableau",
    "Power BI",
    "Google Analytics",
    "Pandas",
    "Statistics",
    "Data Visualization",
    "ETL",
    "BigQuery",
    "Looker",
    "JIRA",
    "Reporting",
  ],
  "Data Engineer": [
    "Python",
    "SQL",
    "Apache Spark",
    "Hadoop",
    "Kafka",
    "Airflow",
    "AWS",
    "GCP",
    "BigQuery",
    "Redshift",
    "ETL",
    "dbt",
    "Docker",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "CI/CD",
  ],
  "Business Intelligence Analyst": [
    "SQL",
    "Tableau",
    "Power BI",
    "Excel",
    "Python",
    "Google Analytics",
    "Looker",
    "Data Modeling",
    "ETL",
    "Reporting",
    "DAX",
    "Statistics",
  ],
  "AI Research Scientist": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Reinforcement Learning",
    "Statistics",
    "Mathematics",
    "Research Writing",
    "Jupyter",
    "Git",
    "CUDA",
    "Transformers",
  ],

  //Product
  "Product Manager": [
    "Product Roadmap",
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "A/B Testing",
    "SQL",
    "Figma",
    "Stakeholder Management",
    "PRD Writing",
    "Data Analysis",
    "Go-to-Market Strategy",
    "OKRs",
  ],
  "Associate Product Manager": [
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "Figma",
    "SQL",
    "A/B Testing",
    "Product Roadmap",
    "Stakeholder Communication",
  ],
  "Senior Product Manager": [
    "Product Strategy",
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "A/B Testing",
    "SQL",
    "Figma",
    "Stakeholder Management",
    "PRD Writing",
    "Go-to-Market Strategy",
    "OKRs",
    "Team Leadership",
  ],
  "Technical Product Manager": [
    "SQL",
    "APIs",
    "Agile",
    "Scrum",
    "JIRA",
    "System Design",
    "User Research",
    "Figma",
    "Data Analysis",
    "Product Roadmap",
    "Engineering Collaboration",
    "OKRs",
  ],
  "Product Owner": [
    "Agile",
    "Scrum",
    "JIRA",
    "Backlog Management",
    "User Stories",
    "Sprint Planning",
    "Stakeholder Management",
    "Figma",
    "SQL",
  ],

  //Design
  "UI Designer": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "HTML",
    "CSS",
    "Typography",
    "Color Theory",
    "Design Systems",
    "Prototyping",
    "Responsive Design",
    "Zeplin",
    "InVision",
  ],
  "UX Designer": [
    "Figma",
    "Adobe XD",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Usability Testing",
    "Information Architecture",
    "Design Thinking",
    "Sketch",
    "InVision",
    "Journey Mapping",
  ],
  "Product Designer": [
    "Figma",
    "Adobe XD",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Usability Testing",
    "HTML",
    "CSS",
    "Design Thinking",
    "Sketch",
  ],
  "Graphic Designer": [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Figma",
    "Typography",
    "Color Theory",
    "Branding",
    "Print Design",
    "Motion Graphics",
    "Canva",
  ],
  "Motion Designer": [
    "Adobe After Effects",
    "Adobe Premiere Pro",
    "Cinema 4D",
    "Blender",
    "Adobe Illustrator",
    "Figma",
    "Motion Graphics",
    "3D Animation",
    "Storyboarding",
    "Video Editing",
  ],
  "Brand Designer": [
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Figma",
    "Typography",
    "Color Theory",
    "Branding",
    "Logo Design",
    "Brand Guidelines",
    "Adobe InDesign",
    "Canva",
  ],

  //Marketing
  "Marketing Manager": [
    "Digital Marketing",
    "SEO",
    "SEM",
    "Google Analytics",
    "Content Strategy",
    "Social Media",
    "Email Marketing",
    "CRM",
    "HubSpot",
    "Campaign Management",
    "A/B Testing",
    "Copywriting",
    "Budget Management",
  ],
  "Content Writer": [
    "Copywriting",
    "SEO",
    "WordPress",
    "Content Strategy",
    "Blogging",
    "Social Media",
    "Research",
    "Editing",
    "Proofreading",
    "Google Analytics",
  ],
  "SEO Specialist": [
    "SEO",
    "Google Analytics",
    "Google Search Console",
    "Ahrefs",
    "SEMrush",
    "Keyword Research",
    "On-page SEO",
    "Off-page SEO",
    "Link Building",
    "Technical SEO",
    "Content Strategy",
    "WordPress",
  ],
  "Social Media Manager": [
    "Social Media Strategy",
    "Content Creation",
    "Copywriting",
    "Canva",
    "Facebook Ads",
    "Instagram Ads",
    "TikTok",
    "Analytics",
    "Community Management",
    "Hootsuite",
    "Buffer",
  ],
  "Growth Marketer": [
    "A/B Testing",
    "SEO",
    "SEM",
    "Google Ads",
    "Facebook Ads",
    "Email Marketing",
    "SQL",
    "Google Analytics",
    "Funnel Optimization",
    "CRO",
    "HubSpot",
    "Python",
  ],
  "Email Marketing Specialist": [
    "Email Marketing",
    "Mailchimp",
    "HubSpot",
    "Copywriting",
    "A/B Testing",
    "Segmentation",
    "Automation",
    "HTML",
    "CSS",
    "Analytics",
  ],
  "Performance Marketer": [
    "Google Ads",
    "Facebook Ads",
    "TikTok Ads",
    "SEM",
    "A/B Testing",
    "Analytics",
    "CRO",
    "Funnel Optimization",
    "Budget Management",
    "Retargeting",
    "Google Analytics",
  ],

  //Sales
  "Sales Executive": [
    "Lead Generation",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Cold Calling",
    "B2B Sales",
    "Pipeline Management",
    "Communication",
    "Networking",
  ],
  "Business Development Manager": [
    "Business Development",
    "Lead Generation",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Partnerships",
    "B2B Sales",
    "Market Research",
    "Stakeholder Management",
    "Networking",
  ],
  "Account Manager": [
    "Account Management",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Client Relations",
    "Upselling",
    "Communication",
    "Pipeline Management",
  ],
  "Sales Development Representative": [
    "Lead Generation",
    "Cold Calling",
    "Email Outreach",
    "CRM",
    "Salesforce",
    "Communication",
    "LinkedIn Sales Navigator",
    "Pipeline Management",
  ],
  "Enterprise Sales Manager": [
    "Enterprise Sales",
    "B2B Sales",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Stakeholder Management",
    "Pipeline Management",
    "Team Leadership",
    "Partnerships",
    "Contract Management",
  ],

  //Finance
  "Financial Analyst": [
    "Financial Modeling",
    "Excel",
    "SQL",
    "Tableau",
    "Power BI",
    "Accounting",
    "Budgeting",
    "Forecasting",
    "Valuation",
    "Bloomberg",
  ],
  Accountant: [
    "Accounting",
    "Excel",
    "QuickBooks",
    "Tally",
    "Tax Compliance",
    "Budgeting",
    "Financial Reporting",
    "Auditing",
    "Payroll",
    "GAAP",
  ],
  "Finance Manager": [
    "Financial Modeling",
    "Excel",
    "Budgeting",
    "Forecasting",
    "Financial Reporting",
    "Accounting",
    "ERP Systems",
    "Team Leadership",
    "Tax Compliance",
    "Auditing",
  ],
  "Chief Financial Officer": [
    "Financial Strategy",
    "Budgeting",
    "Forecasting",
    "Financial Modeling",
    "Accounting",
    "Investor Relations",
    "Risk Management",
    "ERP Systems",
    "Team Leadership",
    "Compliance",
    "M&A",
  ],
  "Investment Analyst": [
    "Financial Modeling",
    "Valuation",
    "Excel",
    "Bloomberg",
    "SQL",
    "Equity Research",
    "Portfolio Management",
    "Due Diligence",
    "Financial Reporting",
    "Statistics",
  ],

  //Human Resources
  "HR Manager": [
    "Recruitment",
    "Onboarding",
    "Performance Management",
    "HRIS",
    "Employee Relations",
    "Compliance",
    "Payroll",
    "Training & Development",
    "Conflict Resolution",
    "Labor Law",
  ],
  "HR Generalist": [
    "Recruitment",
    "Onboarding",
    "HRIS",
    "Employee Relations",
    "Payroll",
    "Compliance",
    "Performance Management",
    "Labor Law",
  ],
  "Talent Acquisition Specialist": [
    "Recruitment",
    "Sourcing",
    "LinkedIn Recruiter",
    "ATS",
    "Interviewing",
    "Employer Branding",
    "Onboarding",
    "Job Posting",
    "Negotiation",
  ],
  "Compensation & Benefits Analyst": [
    "Compensation Analysis",
    "Benefits Administration",
    "Excel",
    "HRIS",
    "Payroll",
    "Labor Law",
    "Data Analysis",
    "Reporting",
  ],
  "HR Business Partner": [
    "HR Strategy",
    "Employee Relations",
    "Performance Management",
    "HRIS",
    "Recruitment",
    "Compliance",
    "Stakeholder Management",
    "Labor Law",
    "Change Management",
    "Training & Development",
  ],

  //Operations
  "Operations Manager": [
    "Operations Management",
    "Process Improvement",
    "Budgeting",
    "ERP Systems",
    "Supply Chain",
    "Team Leadership",
    "KPI Tracking",
    "Agile",
    "JIRA",
  ],
  "Project Manager": [
    "Project Management",
    "Agile",
    "Scrum",
    "JIRA",
    "Risk Management",
    "Stakeholder Management",
    "Budgeting",
    "MS Project",
    "PMP",
    "Kanban",
  ],
  "Scrum Master": [
    "Scrum",
    "Agile",
    "JIRA",
    "Sprint Planning",
    "Backlog Management",
    "Team Facilitation",
    "Kanban",
    "Conflict Resolution",
    "Coaching",
  ],
  "Business Analyst": [
    "Requirements Gathering",
    "SQL",
    "JIRA",
    "Process Mapping",
    "Agile",
    "Stakeholder Management",
    "Data Analysis",
    "Figma",
    "Excel",
    "Reporting",
  ],
  "Supply Chain Manager": [
    "Supply Chain Management",
    "Logistics",
    "ERP Systems",
    "Inventory Management",
    "Procurement",
    "Vendor Management",
    "Excel",
    "SAP",
    "Forecasting",
  ],

  //Legal
  "Legal Counsel": [
    "Contract Law",
    "Corporate Law",
    "Legal Research",
    "Drafting",
    "Compliance",
    "Negotiation",
    "Litigation",
    "Intellectual Property",
    "Labor Law",
    "Risk Management",
  ],
  "Compliance Officer": [
    "Compliance",
    "Risk Management",
    "Regulatory Frameworks",
    "Auditing",
    "Legal Research",
    "Policy Development",
    "AML",
    "KYC",
    "Reporting",
  ],
  "Contract Manager": [
    "Contract Management",
    "Drafting",
    "Negotiation",
    "Legal Research",
    "Compliance",
    "Risk Management",
    "Vendor Management",
    "Excel",
  ],

  //Customer Support
  "Customer Support Specialist": [
    "Customer Service",
    "CRM",
    "Zendesk",
    "Communication",
    "Problem Solving",
    "Email Support",
    "Live Chat",
    "Ticketing Systems",
    "Empathy",
  ],
  "Technical Support Engineer": [
    "Technical Troubleshooting",
    "Networking",
    "Linux",
    "Windows",
    "CRM",
    "Zendesk",
    "SQL",
    "REST APIs",
    "Communication",
    "Ticketing Systems",
  ],
  "Customer Success Manager": [
    "Account Management",
    "CRM",
    "Salesforce",
    "Onboarding",
    "Upselling",
    "Client Relations",
    "Communication",
    "Data Analysis",
    "Retention",
  ],

  //Research
  "Research Scientist": [
    "Research Methodology",
    "Python",
    "R",
    "Statistics",
    "Data Analysis",
    "Academic Writing",
    "Literature Review",
    "MATLAB",
    "Experiment Design",
  ],
  "Research Analyst": [
    "Research Methodology",
    "SQL",
    "Excel",
    "Python",
    "Statistics",
    "Data Visualization",
    "Reporting",
    "Market Research",
    "Literature Review",
  ],
  "UX Researcher": [
    "User Research",
    "Usability Testing",
    "Interviews",
    "Surveys",
    "Figma",
    "Data Analysis",
    "Journey Mapping",
    "Research Methodology",
    "Affinity Mapping",
    "A/B Testing",
  ],
};
export {
  POSITIONS,
  EXPERIENCE_LEVELS,
  HR_DESIGNATIONS,
  DEPARTMENTS,
  NEPAL_LOCATIONS,
  JOB_STATUS,
  POSITION_SKILLS,
  POSITION_DEPARTMENT_MAP,
  INTERVIEW_TONE,
};
