// Mirror of Backend/types/index.js — single source of truth for enums shared
// between the frontend form UI and the backend validation layer.

export const POSITIONS: string[] = [
  // Engineering
  "Frontend Engineer",
  "Backend Engineer",
  "Full Stack Engineer",
  "Mobile Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "QA Engineer",
  "Security Engineer",
  "Machine Learning Engineer",
  "Embedded Systems Engineer",
  "Blockchain Developer",
  // Data & Analytics
  "Data Scientist",
  "Data Analyst",
  "Data Engineer",
  "Business Intelligence Analyst",
  "AI Research Scientist",
  // Product
  "Product Manager",
  "Associate Product Manager",
  "Senior Product Manager",
  "Technical Product Manager",
  "Product Owner",
  // Design
  "UI Designer",
  "UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Motion Designer",
  "Brand Designer",
  // Marketing
  "Marketing Manager",
  "Content Writer",
  "SEO Specialist",
  "Social Media Manager",
  "Growth Marketer",
  "Email Marketing Specialist",
  "Performance Marketer",
  // Sales
  "Sales Executive",
  "Business Development Manager",
  "Account Manager",
  "Sales Development Representative",
  "Enterprise Sales Manager",
  // Finance
  "Financial Analyst",
  "Accountant",
  "Finance Manager",
  "Chief Financial Officer",
  "Investment Analyst",
  // Human Resources
  "HR Manager",
  "HR Generalist",
  "Talent Acquisition Specialist",
  "Compensation & Benefits Analyst",
  "HR Business Partner",
  // Operations
  "Operations Manager",
  "Project Manager",
  "Scrum Master",
  "Business Analyst",
  "Supply Chain Manager",
  // Legal
  "Legal Counsel",
  "Compliance Officer",
  "Contract Manager",
  // Customer Support
  "Customer Support Specialist",
  "Technical Support Engineer",
  "Customer Success Manager",
  // Research
  "Research Scientist",
  "Research Analyst",
  "UX Researcher",
];

/** Positions grouped by department for a better dropdown experience. */
export const POSITIONS_BY_DEPARTMENT: {
  department: string;
  positions: string[];
}[] = [
  {
    department: "Engineering",
    positions: [
      "Frontend Engineer",
      "Backend Engineer",
      "Full Stack Engineer",
      "Mobile Engineer",
      "DevOps Engineer",
      "Site Reliability Engineer",
      "QA Engineer",
      "Security Engineer",
      "Machine Learning Engineer",
      "Embedded Systems Engineer",
      "Blockchain Developer",
    ],
  },
  {
    department: "Data & Analytics",
    positions: [
      "Data Scientist",
      "Data Analyst",
      "Data Engineer",
      "Business Intelligence Analyst",
      "AI Research Scientist",
    ],
  },
  {
    department: "Product",
    positions: [
      "Product Manager",
      "Associate Product Manager",
      "Senior Product Manager",
      "Technical Product Manager",
      "Product Owner",
    ],
  },
  {
    department: "Design",
    positions: [
      "UI Designer",
      "UX Designer",
      "Product Designer",
      "Graphic Designer",
      "Motion Designer",
      "Brand Designer",
    ],
  },
  {
    department: "Marketing",
    positions: [
      "Marketing Manager",
      "Content Writer",
      "SEO Specialist",
      "Social Media Manager",
      "Growth Marketer",
      "Email Marketing Specialist",
      "Performance Marketer",
    ],
  },
  {
    department: "Sales",
    positions: [
      "Sales Executive",
      "Business Development Manager",
      "Account Manager",
      "Sales Development Representative",
      "Enterprise Sales Manager",
    ],
  },
  {
    department: "Finance",
    positions: [
      "Financial Analyst",
      "Accountant",
      "Finance Manager",
      "Chief Financial Officer",
      "Investment Analyst",
    ],
  },
  {
    department: "Human Resources",
    positions: [
      "HR Manager",
      "HR Generalist",
      "Talent Acquisition Specialist",
      "Compensation & Benefits Analyst",
      "HR Business Partner",
    ],
  },
  {
    department: "Operations",
    positions: [
      "Operations Manager",
      "Project Manager",
      "Scrum Master",
      "Business Analyst",
      "Supply Chain Manager",
    ],
  },
  {
    department: "Legal",
    positions: ["Legal Counsel", "Compliance Officer", "Contract Manager"],
  },
  {
    department: "Customer Support",
    positions: [
      "Customer Support Specialist",
      "Technical Support Engineer",
      "Customer Success Manager",
    ],
  },
  {
    department: "Research",
    positions: ["Research Scientist", "Research Analyst", "UX Researcher"],
  },
];

export const EXPERIENCE_LEVELS: string[] = [
  "Internship",
  "Entry Level",
  "Junior",
  "Mid Level",
  "Senior",
];

export const DEPARTMENTS: string[] = [
  "Engineering",
  "Data & Analytics",
  "Product",
  "Design",
  "Marketing",
  "Sales",
  "Finance",
  "Human Resources",
  "Operations",
  "Legal",
  "Customer Support",
  "Research",
];

export const JOB_STATUS: string[] = ["Draft", "Published", "Closed"];

export const INTERVIEW_TONE: string[] = [
  "formal",
  "casual",
  "technical",
  "behavioral",
  "mixed",
];

export const NEPAL_LOCATIONS: string[] = [
  "Morang, Biratnagar",
  "Sunsari, Itahari",
  "Sunsari, Dharan",
  "Jhapa, Birtamod",
  "Jhapa, Mechinagar",
  "Ilam, Ilam",
  "Dhankuta, Dhankuta",
  "Udayapur, Gaighat",
  "Parsa, Birgunj",
  "Bara, Kalaiya",
  "Dhanusha, Janakpur",
  "Sarlahi, Malangwa",
  "Saptari, Rajbiraj",
  "Kathmandu, Kathmandu",
  "Kathmandu, Kirtipur",
  "Lalitpur, Lalitpur",
  "Bhaktapur, Bhaktapur",
  "Bhaktapur, Madhyapur Thimi",
  "Chitwan, Bharatpur",
  "Makwanpur, Hetauda",
  "Kavrepalanchok, Dhulikhel",
  "Kavrepalanchok, Banepa",
  "Sindhupalchok, Chautara",
  "Nuwakot, Bidur",
  "Dhading, Nilkantha",
  "Kaski, Pokhara",
  "Tanahun, Damauli",
  "Syangja, Waling",
  "Gorkha, Gorkha",
  "Lamjung, Besisahar",
  "Baglung, Baglung",
  "Rupandehi, Butwal",
  "Rupandehi, Siddharthanagar",
  "Banke, Nepalgunj",
  "Dang, Ghorahi",
  "Dang, Tulsipur",
  "Bardiya, Gulariya",
  "Kapilvastu, Taulihawa",
  "Palpa, Tansen",
  "Surkhet, Birendranagar",
  "Jumla, Chandannath",
  "Dailekh, Narayan",
  "Salyan, Sharada",
  "Kailali, Dhangadhi",
  "Kailali, Tikapur",
  "Kanchanpur, Mahendranagar",
  "Dadeldhura, Dadeldhura",
  "Doti, Dipayal",
  "Achham, Mangalsen",
  "Baitadi, Dasharathchand",
];

export const POSITION_DEPARTMENT_MAP: Record<string, string> = {
  "Frontend Engineer": "Engineering",
  "Backend Engineer": "Engineering",
  "Full Stack Engineer": "Engineering",
  "Mobile Engineer": "Engineering",
  "DevOps Engineer": "Engineering",
  "Site Reliability Engineer": "Engineering",
  "QA Engineer": "Engineering",
  "Security Engineer": "Engineering",
  "Machine Learning Engineer": "Engineering",
  "Embedded Systems Engineer": "Engineering",
  "Blockchain Developer": "Engineering",
  "Data Scientist": "Data & Analytics",
  "Data Analyst": "Data & Analytics",
  "Data Engineer": "Data & Analytics",
  "Business Intelligence Analyst": "Data & Analytics",
  "AI Research Scientist": "Data & Analytics",
  "Product Manager": "Product",
  "Associate Product Manager": "Product",
  "Senior Product Manager": "Product",
  "Technical Product Manager": "Product",
  "Product Owner": "Product",
  "UI Designer": "Design",
  "UX Designer": "Design",
  "Product Designer": "Design",
  "Graphic Designer": "Design",
  "Motion Designer": "Design",
  "Brand Designer": "Design",
  "Marketing Manager": "Marketing",
  "Content Writer": "Marketing",
  "SEO Specialist": "Marketing",
  "Social Media Manager": "Marketing",
  "Growth Marketer": "Marketing",
  "Email Marketing Specialist": "Marketing",
  "Performance Marketer": "Marketing",
  "Sales Executive": "Sales",
  "Business Development Manager": "Sales",
  "Account Manager": "Sales",
  "Sales Development Representative": "Sales",
  "Enterprise Sales Manager": "Sales",
  "Financial Analyst": "Finance",
  Accountant: "Finance",
  "Finance Manager": "Finance",
  "Chief Financial Officer": "Finance",
  "Investment Analyst": "Finance",
  "HR Manager": "Human Resources",
  "HR Generalist": "Human Resources",
  "Talent Acquisition Specialist": "Human Resources",
  "Compensation & Benefits Analyst": "Human Resources",
  "HR Business Partner": "Human Resources",
  "Operations Manager": "Operations",
  "Project Manager": "Operations",
  "Scrum Master": "Operations",
  "Business Analyst": "Operations",
  "Supply Chain Manager": "Operations",
  "Legal Counsel": "Legal",
  "Compliance Officer": "Legal",
  "Contract Manager": "Legal",
  "Customer Support Specialist": "Customer Support",
  "Technical Support Engineer": "Customer Support",
  "Customer Success Manager": "Customer Support",
  "Research Scientist": "Research",
  "Research Analyst": "Research",
  "UX Researcher": "Research",
};

export const POSITION_SKILLS: Record<string, string[]> = {
  "Frontend Engineer": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "Tailwind CSS",
    "Redux",
    "GraphQL",
    "REST APIs",
    "Git",
    "Webpack",
    "Vite",
    "Jest",
    "Cypress",
    "Figma",
    "Responsive Design",
  ],
  "Backend Engineer": [
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "FastAPI",
    "Java",
    "Spring Boot",
    "Go",
    "Ruby on Rails",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Redis",
    "REST APIs",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "AWS",
    "Git",
    "CI/CD",
  ],
  "Full Stack Engineer": [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Express.js",
    "PostgreSQL",
    "MongoDB",
    "REST APIs",
    "GraphQL",
    "Docker",
    "Git",
    "AWS",
    "Redis",
    "CI/CD",
    "Tailwind CSS",
  ],
  "Mobile Engineer": [
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Java",
    "Dart",
    "iOS Development",
    "Android Development",
    "Firebase",
    "REST APIs",
    "GraphQL",
    "Redux",
    "Git",
    "App Store Deployment",
    "Push Notifications",
  ],
  "DevOps Engineer": [
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Azure",
    "Terraform",
    "Ansible",
    "Jenkins",
    "CI/CD",
    "Linux",
    "Bash",
    "Python",
    "Nginx",
    "Git",
    "Prometheus",
    "Grafana",
    "Helm",
    "ArgoCD",
  ],
  "Site Reliability Engineer": [
    "Linux",
    "Docker",
    "Kubernetes",
    "AWS",
    "GCP",
    "Terraform",
    "Python",
    "Bash",
    "Prometheus",
    "Grafana",
    "CI/CD",
    "Incident Management",
    "Load Balancing",
    "Nginx",
    "Git",
    "On-call Management",
  ],
  "QA Engineer": [
    "Manual Testing",
    "Automation Testing",
    "Selenium",
    "Cypress",
    "Jest",
    "Postman",
    "REST APIs",
    "SQL",
    "Git",
    "JIRA",
    "Test Planning",
    "Performance Testing",
    "JMeter",
    "Bug Tracking",
    "Agile",
  ],
  "Security Engineer": [
    "Network Security",
    "Penetration Testing",
    "OWASP",
    "AWS Security",
    "Cryptography",
    "SIEM",
    "Firewalls",
    "Linux",
    "Python",
    "Bash",
    "Vulnerability Assessment",
    "IAM",
    "Zero Trust",
    "GDPR Compliance",
  ],
  "Machine Learning Engineer": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "SQL",
    "MLflow",
    "Docker",
    "AWS SageMaker",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Feature Engineering",
    "Git",
    "Jupyter",
  ],
  "Embedded Systems Engineer": [
    "C",
    "C++",
    "RTOS",
    "Microcontrollers",
    "Arduino",
    "Raspberry Pi",
    "ARM Architecture",
    "Assembly",
    "I2C",
    "SPI",
    "UART",
    "CAN Bus",
    "PCB Design",
    "MATLAB",
    "Debugging",
    "Git",
  ],
  "Blockchain Developer": [
    "Solidity",
    "Ethereum",
    "Web3.js",
    "Ethers.js",
    "Smart Contracts",
    "Hardhat",
    "Truffle",
    "IPFS",
    "DeFi",
    "NFT",
    "Rust",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Git",
  ],
  "Data Scientist": [
    "Python",
    "R",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "SQL",
    "Tableau",
    "Power BI",
    "Statistics",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Data Visualization",
    "Jupyter",
    "Git",
  ],
  "Data Analyst": [
    "SQL",
    "Python",
    "Excel",
    "Tableau",
    "Power BI",
    "Google Analytics",
    "Pandas",
    "Statistics",
    "Data Visualization",
    "ETL",
    "BigQuery",
    "Looker",
    "JIRA",
    "Reporting",
  ],
  "Data Engineer": [
    "Python",
    "SQL",
    "Apache Spark",
    "Hadoop",
    "Kafka",
    "Airflow",
    "AWS",
    "GCP",
    "BigQuery",
    "Redshift",
    "ETL",
    "dbt",
    "Docker",
    "PostgreSQL",
    "MongoDB",
    "Git",
    "CI/CD",
  ],
  "Business Intelligence Analyst": [
    "SQL",
    "Tableau",
    "Power BI",
    "Excel",
    "Python",
    "Google Analytics",
    "Looker",
    "Data Modeling",
    "ETL",
    "Reporting",
    "DAX",
    "Statistics",
  ],
  "AI Research Scientist": [
    "Python",
    "TensorFlow",
    "PyTorch",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "Reinforcement Learning",
    "Statistics",
    "Mathematics",
    "Research Writing",
    "Jupyter",
    "Git",
    "CUDA",
    "Transformers",
  ],
  "Product Manager": [
    "Product Roadmap",
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "A/B Testing",
    "SQL",
    "Figma",
    "Stakeholder Management",
    "PRD Writing",
    "Data Analysis",
    "Go-to-Market Strategy",
    "OKRs",
  ],
  "Associate Product Manager": [
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "Figma",
    "SQL",
    "A/B Testing",
    "Product Roadmap",
    "Stakeholder Communication",
  ],
  "Senior Product Manager": [
    "Product Strategy",
    "Agile",
    "Scrum",
    "JIRA",
    "User Research",
    "A/B Testing",
    "SQL",
    "Figma",
    "Stakeholder Management",
    "PRD Writing",
    "Go-to-Market Strategy",
    "OKRs",
    "Team Leadership",
  ],
  "Technical Product Manager": [
    "SQL",
    "APIs",
    "Agile",
    "Scrum",
    "JIRA",
    "System Design",
    "User Research",
    "Figma",
    "Data Analysis",
    "Product Roadmap",
    "Engineering Collaboration",
    "OKRs",
  ],
  "Product Owner": [
    "Agile",
    "Scrum",
    "JIRA",
    "Backlog Management",
    "User Stories",
    "Sprint Planning",
    "Stakeholder Management",
    "Figma",
    "SQL",
  ],
  "UI Designer": [
    "Figma",
    "Adobe XD",
    "Sketch",
    "HTML",
    "CSS",
    "Typography",
    "Color Theory",
    "Design Systems",
    "Prototyping",
    "Responsive Design",
    "Zeplin",
    "InVision",
  ],
  "UX Designer": [
    "Figma",
    "Adobe XD",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Usability Testing",
    "Information Architecture",
    "Design Thinking",
    "Sketch",
    "InVision",
    "Journey Mapping",
  ],
  "Product Designer": [
    "Figma",
    "Adobe XD",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Usability Testing",
    "HTML",
    "CSS",
    "Design Thinking",
    "Sketch",
  ],
  "Graphic Designer": [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Figma",
    "Typography",
    "Color Theory",
    "Branding",
    "Print Design",
    "Motion Graphics",
    "Canva",
  ],
  "Motion Designer": [
    "Adobe After Effects",
    "Adobe Premiere Pro",
    "Cinema 4D",
    "Blender",
    "Adobe Illustrator",
    "Figma",
    "Motion Graphics",
    "3D Animation",
    "Storyboarding",
    "Video Editing",
  ],
  "Brand Designer": [
    "Adobe Illustrator",
    "Adobe Photoshop",
    "Figma",
    "Typography",
    "Color Theory",
    "Branding",
    "Logo Design",
    "Brand Guidelines",
    "Adobe InDesign",
    "Canva",
  ],
  "Marketing Manager": [
    "Digital Marketing",
    "SEO",
    "SEM",
    "Google Analytics",
    "Content Strategy",
    "Social Media",
    "Email Marketing",
    "CRM",
    "HubSpot",
    "Campaign Management",
    "A/B Testing",
    "Copywriting",
    "Budget Management",
  ],
  "Content Writer": [
    "Copywriting",
    "SEO",
    "WordPress",
    "Content Strategy",
    "Blogging",
    "Social Media",
    "Research",
    "Editing",
    "Proofreading",
    "Google Analytics",
  ],
  "SEO Specialist": [
    "SEO",
    "Google Analytics",
    "Google Search Console",
    "Ahrefs",
    "SEMrush",
    "Keyword Research",
    "On-page SEO",
    "Off-page SEO",
    "Link Building",
    "Technical SEO",
    "Content Strategy",
    "WordPress",
  ],
  "Social Media Manager": [
    "Social Media Strategy",
    "Content Creation",
    "Copywriting",
    "Canva",
    "Facebook Ads",
    "Instagram Ads",
    "TikTok",
    "Analytics",
    "Community Management",
    "Hootsuite",
    "Buffer",
  ],
  "Growth Marketer": [
    "A/B Testing",
    "SEO",
    "SEM",
    "Google Ads",
    "Facebook Ads",
    "Email Marketing",
    "SQL",
    "Google Analytics",
    "Funnel Optimization",
    "CRO",
    "HubSpot",
    "Python",
  ],
  "Email Marketing Specialist": [
    "Email Marketing",
    "Mailchimp",
    "HubSpot",
    "Copywriting",
    "A/B Testing",
    "Segmentation",
    "Automation",
    "HTML",
    "CSS",
    "Analytics",
  ],
  "Performance Marketer": [
    "Google Ads",
    "Facebook Ads",
    "TikTok Ads",
    "SEM",
    "A/B Testing",
    "Analytics",
    "CRO",
    "Funnel Optimization",
    "Budget Management",
    "Retargeting",
    "Google Analytics",
  ],
  "Sales Executive": [
    "Lead Generation",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Cold Calling",
    "B2B Sales",
    "Pipeline Management",
    "Communication",
    "Networking",
  ],
  "Business Development Manager": [
    "Business Development",
    "Lead Generation",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Partnerships",
    "B2B Sales",
    "Market Research",
    "Stakeholder Management",
    "Networking",
  ],
  "Account Manager": [
    "Account Management",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Client Relations",
    "Upselling",
    "Communication",
    "Pipeline Management",
  ],
  "Sales Development Representative": [
    "Lead Generation",
    "Cold Calling",
    "Email Outreach",
    "CRM",
    "Salesforce",
    "Communication",
    "LinkedIn Sales Navigator",
    "Pipeline Management",
  ],
  "Enterprise Sales Manager": [
    "Enterprise Sales",
    "B2B Sales",
    "CRM",
    "Salesforce",
    "Negotiation",
    "Stakeholder Management",
    "Pipeline Management",
    "Team Leadership",
    "Partnerships",
    "Contract Management",
  ],
  "Financial Analyst": [
    "Financial Modeling",
    "Excel",
    "SQL",
    "Tableau",
    "Power BI",
    "Accounting",
    "Budgeting",
    "Forecasting",
    "Valuation",
    "Bloomberg",
  ],
  Accountant: [
    "Accounting",
    "Excel",
    "QuickBooks",
    "Tally",
    "Tax Compliance",
    "Budgeting",
    "Financial Reporting",
    "Auditing",
    "Payroll",
    "GAAP",
  ],
  "Finance Manager": [
    "Financial Modeling",
    "Excel",
    "Budgeting",
    "Forecasting",
    "Financial Reporting",
    "Accounting",
    "ERP Systems",
    "Team Leadership",
    "Tax Compliance",
    "Auditing",
  ],
  "Chief Financial Officer": [
    "Financial Strategy",
    "Budgeting",
    "Forecasting",
    "Financial Modeling",
    "Accounting",
    "Investor Relations",
    "Risk Management",
    "ERP Systems",
    "Team Leadership",
    "Compliance",
    "M&A",
  ],
  "Investment Analyst": [
    "Financial Modeling",
    "Valuation",
    "Excel",
    "Bloomberg",
    "SQL",
    "Equity Research",
    "Portfolio Management",
    "Due Diligence",
    "Financial Reporting",
    "Statistics",
  ],
  "HR Manager": [
    "Recruitment",
    "Onboarding",
    "Performance Management",
    "HRIS",
    "Employee Relations",
    "Compliance",
    "Payroll",
    "Training & Development",
    "Conflict Resolution",
    "Labor Law",
  ],
  "HR Generalist": [
    "Recruitment",
    "Onboarding",
    "HRIS",
    "Employee Relations",
    "Payroll",
    "Compliance",
    "Performance Management",
    "Labor Law",
  ],
  "Talent Acquisition Specialist": [
    "Recruitment",
    "Sourcing",
    "LinkedIn Recruiter",
    "ATS",
    "Interviewing",
    "Employer Branding",
    "Onboarding",
    "Job Posting",
    "Negotiation",
  ],
  "Compensation & Benefits Analyst": [
    "Compensation Analysis",
    "Benefits Administration",
    "Excel",
    "HRIS",
    "Payroll",
    "Labor Law",
    "Data Analysis",
    "Reporting",
  ],
  "HR Business Partner": [
    "HR Strategy",
    "Employee Relations",
    "Performance Management",
    "HRIS",
    "Recruitment",
    "Compliance",
    "Stakeholder Management",
    "Labor Law",
    "Change Management",
    "Training & Development",
  ],
  "Operations Manager": [
    "Operations Management",
    "Process Improvement",
    "Budgeting",
    "ERP Systems",
    "Supply Chain",
    "Team Leadership",
    "KPI Tracking",
    "Agile",
    "JIRA",
  ],
  "Project Manager": [
    "Project Management",
    "Agile",
    "Scrum",
    "JIRA",
    "Risk Management",
    "Stakeholder Management",
    "Budgeting",
    "MS Project",
    "PMP",
    "Kanban",
  ],
  "Scrum Master": [
    "Scrum",
    "Agile",
    "JIRA",
    "Sprint Planning",
    "Backlog Management",
    "Team Facilitation",
    "Kanban",
    "Conflict Resolution",
    "Coaching",
  ],
  "Business Analyst": [
    "Requirements Gathering",
    "SQL",
    "JIRA",
    "Process Mapping",
    "Agile",
    "Stakeholder Management",
    "Data Analysis",
    "Figma",
    "Excel",
    "Reporting",
  ],
  "Supply Chain Manager": [
    "Supply Chain Management",
    "Logistics",
    "ERP Systems",
    "Inventory Management",
    "Procurement",
    "Vendor Management",
    "Excel",
    "SAP",
    "Forecasting",
  ],
  "Legal Counsel": [
    "Contract Law",
    "Corporate Law",
    "Legal Research",
    "Drafting",
    "Compliance",
    "Negotiation",
    "Litigation",
    "Intellectual Property",
    "Labor Law",
    "Risk Management",
  ],
  "Compliance Officer": [
    "Compliance",
    "Risk Management",
    "Regulatory Frameworks",
    "Auditing",
    "Legal Research",
    "Policy Development",
    "AML",
    "KYC",
    "Reporting",
  ],
  "Contract Manager": [
    "Contract Management",
    "Drafting",
    "Negotiation",
    "Legal Research",
    "Compliance",
    "Risk Management",
    "Vendor Management",
    "Excel",
  ],
  "Customer Support Specialist": [
    "Customer Service",
    "CRM",
    "Zendesk",
    "Communication",
    "Problem Solving",
    "Email Support",
    "Live Chat",
    "Ticketing Systems",
    "Empathy",
  ],
  "Technical Support Engineer": [
    "Technical Troubleshooting",
    "Networking",
    "Linux",
    "Windows",
    "CRM",
    "Zendesk",
    "SQL",
    "REST APIs",
    "Communication",
    "Ticketing Systems",
  ],
  "Customer Success Manager": [
    "Account Management",
    "CRM",
    "Salesforce",
    "Onboarding",
    "Upselling",
    "Client Relations",
    "Communication",
    "Data Analysis",
    "Retention",
  ],
  "Research Scientist": [
    "Research Methodology",
    "Python",
    "R",
    "Statistics",
    "Data Analysis",
    "Academic Writing",
    "Literature Review",
    "MATLAB",
    "Experiment Design",
  ],
  "Research Analyst": [
    "Research Methodology",
    "SQL",
    "Excel",
    "Python",
    "Statistics",
    "Data Visualization",
    "Reporting",
    "Market Research",
    "Literature Review",
  ],
  "UX Researcher": [
    "User Research",
    "Usability Testing",
    "Interviews",
    "Surveys",
    "Figma",
    "Data Analysis",
    "Journey Mapping",
    "Research Methodology",
    "Affinity Mapping",
    "A/B Testing",
  ],
};
